name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: jhipsterSampleApplication pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '11.x'
            - uses: graalvm/setup-graalvm@v1
              with:
                 version: '22.3.0'
                 java-version: '11'
                 components: 'native-image'
                 github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Stop MySQL server
              run: sudo /etc/init.d/mysql stop
            - name: Install node.js packages
              run: |
                  npm ci
            - name: Run backend test
              run: ./mvnw -ntp clean test -P-webpack
            - name: Run frontend test
              run: npm run test
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [[ -n "$SONAR_TOKEN" && "$GITHUB_REPOSITORY" = "jhipster/jhipster-sample-app-quarkus" && "$GITHUB_REF" = "refs/heads/main" ]]; then
                      ./mvnw -ntp initialize sonar:sonar -Dsonar.organization=jhipster -Dsonar.host.url=https://sonarcloud.io
                  fi
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests
            - name: Build Native Image and run Integration tests
              run: ./mvnw -ntp verify -Pnative
